apiVersion: 1
datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource # Asegúrate que coincida con el ID del plugin instalado
    uid: ffj59p1czpvr4d
    access: proxy
    url: ${CASSANDRA_URL}         # Dirección y puerto de tu nodo/cluster
    editable: true
    jsonData:
      keyspace: ${CASSANDRA_KEYSPACE}        # Keyspace por defecto para conectar
      consistency: "ONE"        # Nivel de consistencia para las queries
      contactPoints: "localhost"