{
 "title": "Vuelos en Vivo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Panel de Control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total de Vuelos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "columnTime": "last_update",
     "columnValue": "icao24",
     "keyspace": "opensky_analytics",
     "table": "live_flights",
     "target": "SELECT icao24 FROM opensky_analytics.live_flights;"
    }
   ]
  },
  {
   "title": "Velocidad Máxima",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "columnTime": "last_update",
     "keyspace": "opensky_analytics",
     "table": "live_flights",
     "target": "SELECT velocity FROM opensky_analytics.live_flights;"
    }
   ]
  },
  {
   "title": "Altitud Media",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "columnTime": "last_update",
     "keyspace": "opensky_analytics",
     "table": "live_flights",
     "target": "SELECT altitude FROM opensky_analytics.live_flights;"
    }
   ]
  },
  {
   "title": "Velocidad Media",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "columnTime": "last_update",
     "keyspace": "opensky_analytics",
     "table": "live_flights",
     "target": "SELECT velocity FROM opensky_analytics.live_flights;"
    }
   ]
  },
  { "title": "Mapas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Mapa de Calor",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "columnTime": "last_update",
     "keyspace": "opensky_analytics",
     "table": "live_flights",
     "target": "SELECT \n    icao24, \n    latitude, \n    longitude, \n    altitude \nFROM opensky_analytics.live_flights;"
    }
   ]
  },
  {
   "title": "Tabla de Seguimiento Detallada",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "target": "SELECT \n    icao24, \n    callsign, \n    origin_country, \n    velocity, \n    altitude, \n    on_ground\nFROM opensky_analytics.live_flights;"
    }
   ]
  },
  { "title": "Información Variada", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Origen del Tráfico aéreo ",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "target": "SELECT origin_country, icao24 \nFROM opensky_analytics.live_flights;"
    }
   ]
  },
  {
   "title": "Tabla de Baja Altitud",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "target": "SELECT \n    icao24, \n    altitude, \n    ts AS time \nFROM opensky_analytics.flight_alerts \nWHERE alert_type = 'LOW_ALTITUDE' \n  AND ts > toTimestamp(now()) - 1m \nLIMIT 10 \nALLOW FILTERING;"
    }
   ]
  }
 ]
}